### ISSUE TITLE
Enable -Wall -Werror

### ISSUE THREAD

**Issue by DoYouEvenCpp** [stryku/cmakesl#156]
Treating warnings as errors shall be enabled by default in every project.
Also, other handy compiler flags could be enabled.

**Comment by playmer** [comment]
Are you suggesting this for the cmakesl build? Or is this a suggestion that when using cmakesl, projects defined in the new language should have these as default? That's really more of a suggestion for CMake I feel.

**Comment by DoYouEvenCpp** [comment]
> 
> 
> Are you suggesting this for the cmakesl build? Or is this a suggestion that when using cmakesl, projects defined in the new language should have these as default? That's really more of a suggestion for CMake I feel.

My intention was to introduce proper compilation flags into cmakesl build proccess - just as @stryku mentioned above.
